CREATE VIEW VIEWEMPRESA AS SELECT ID, NOME, CNPJ FROM EMPRESA;
SELECT * FROM VIEWEMPRESA;

CREATE VIEW VIEWFORNECEDORES AS SELECT ID, NOME, CNPJ, TIPO_SERVICO FROM FORNECEDORES;
SELECT * FROM VIEWFORNECEDORES;

CREATE VIEW VIEWLOCALIDADES AS SELECT ID, ORIGEM, DESTINO FROM LOCALIDADES;
SELECT * FROM VIEWLOCALIDADES;

CREATE VIEW VIEWPASSAGEIROS AS SELECT ID, NOME, EMAIL, CPF, SEXO, ID_EMPRESA FROM PASSAGEIROS;
SELECT * FROM VIEWPASSAGEIROS;

CREATE VIEW VIEWSOLICITACOES AS SELECT ID, IDPASSAGEIRO, IDFORNECEDOR, IDTARIFA, DATASOLICITACAO FROM SOLICITACOES;
SELECT * FROM VIEWSOLICITACOES;

CREATE VIEW VIEWTARIFA AS SELECT ID, DATAIDA, DATAVOLTA, IDTARIFA, PRECO, IDLOCALIDADE FROM SOLICITACOES;
SELECT * FROM VIEWTARIFA;

CREATE VIEW VIEWPASSAGEIROSPOREMPRESA AS SELECT COUNT(P.ID) AS "TOTAL DE PASSAGEIROS", 
E.NOME AS "EMPRESA" FROM PASSAGEIROS AS P LEFT JOIN EMPRESA AS E ON P.ID_EMPRESA = E.ID GROUP BY EMPRESA;
SELECT * FROM VIEWPASSAGEIROSPOREMPRESA;


